
# this is where the core makefile stuff is
ACLI_DIR := ../ACLI

# include the default configurations
include ${ACLI_DIR}/Arduino_Config.mk


# manually set some stuff...

# force leonardo
FQBN := arduino:avr:leonardo


# put any forced overrides here.

# include the base rules
include ${ACLI_DIR}/Arduino_cli_base.mk
